import type { MassageJourney } from './types'

/**
 * The English journey seed.
 *
 * Every journey answers a question a tourist actually asks themselves — "my
 * legs are wrecked after that ATV tour", "we want something special tonight" —
 * and then quietly names the professional treatment that answers it. The guest
 * never has to learn the vocabulary first.
 *
 * Rules this content keeps to:
 *   - No prices. Those live on the services, which the owner edits.
 *   - No medical claims. Massage here is comfort and rest, never a cure.
 *   - No invented modalities. Every `recommendedServiceIds` entry is a real
 *     service in `seed.ts`.
 *   - `prenatal-safe` is claimed by exactly one journey, and only because it
 *     is delivered as the team's actual Prenatal Massage.
 */
export const journeys: MassageJourney[] = [
  {
    id: 'jrn-arrival',
    slug: 'just-arrived-reset',
    name: 'Just Arrived Reset',
    tagline: 'Your body is still on the plane. Let us bring it here.',
    description:
      'The first massage of the holiday, meant to draw a line under the travelling. Unhurried full-body work that lets your shoulders drop and your holiday actually begin.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-aroma', 'svc-reflex'],
    guestTags: ['just-arrived', 'unsure'],
    occasionTags: ['solo', 'couple', 'first-massage'],
    timingTags: ['arrival-day', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'You just travelled, and travelling leaves the body stiff in odd places.',
      'Slow and warm, so it settles you rather than waking you up.',
      'We can come to your room, so you do not have to go anywhere.',
    ],
    whatToExpect: [
      'A full-body Swedish-style massage at an unhurried pace.',
      'Extra time on the shoulders, lower back and feet — the parts a long flight punishes.',
      'Warm coconut oil, quiet music, and no conversation unless you want one.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Start here',
    image: '',
    featured: true,
    order: 1,
  },
  {
    id: 'jrn-jetlag',
    slug: 'jet-lag-reset',
    name: 'Jet Lag Reset',
    tagline: 'For the night your body insists it is 4am.',
    description:
      'An evening session built around helping you sleep on island time. Long, rhythmic work with a proper focus on the feet, because that is where a body that has crossed time zones tends to hold on.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-reflex', 'svc-stone'],
    guestTags: ['just-arrived', 'switch-off'],
    occasionTags: ['solo', 'couple'],
    timingTags: ['arrival-day', 'evening', 'before-sleep'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'legs-feet'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Your clock is still somewhere over the Atlantic.',
      'Booked for the evening, so you finish already ready for bed.',
      'Gentle enough that nothing wakes you back up.',
    ],
    whatToExpect: [
      'Slow full-body work with long, repeating strokes.',
      'A proper stretch of time on the feet and calves.',
      'Finishing with the scalp and neck, which is what usually tips people over into sleep.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 2,
  },
  {
    id: 'jrn-adventure',
    slug: 'after-adventure-recovery',
    name: 'After Adventure Recovery',
    tagline: 'The buggy was worth it. Your back disagrees.',
    description:
      'For the day after the ATV tour, the catamaran, the zip line or eighteen holes. Firmer, focused work on everything that got shaken, paddled or walked further than usual.',
    recommendedServiceIds: ['svc-deep'],
    alternativeServiceIds: ['svc-back', 'svc-relax'],
    guestTags: ['after-adventure', 'targeted'],
    occasionTags: ['friends', 'couple', 'solo'],
    timingTags: ['after-excursion', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'back-neck-shoulders', 'legs-feet'],
    intensity: 'firm',
    durationMinutes: [60, 90],
    whyItFits: [
      'You did something brilliant yesterday and you can feel all of it today.',
      'Firm, specific pressure where the ache actually is.',
      'You tell us what hurts; we spend the time there.',
    ],
    whatToExpect: [
      'Deep tissue and sports-style work, slower and firmer than a relaxing massage.',
      'Focused attention on the back, shoulders, legs and anywhere you point at.',
      'We check the pressure with you as we go — firm should feel good, never like enduring something.',
    ],
    safetyFlags: [],
    avoidTags: ['pregnant'],
    badge: 'Most booked',
    image: '',
    featured: true,
    order: 3,
  },
  {
    id: 'jrn-feet-legs',
    slug: 'feet-and-legs-reset',
    name: 'Feet & Legs Reset',
    tagline: 'Your legs have had a long day.',
    description:
      'For the beach walkers, the market wanderers and anyone who has been upright since breakfast. All the attention goes below the waist, where the day actually landed.',
    recommendedServiceIds: ['svc-reflex'],
    alternativeServiceIds: ['svc-relax', 'svc-lymph'],
    guestTags: ['after-adventure', 'targeted', 'switch-off'],
    occasionTags: ['solo', 'friends', 'family'],
    timingTags: ['afternoon', 'evening', 'after-excursion'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['legs-feet'],
    intensity: 'balanced',
    durationMinutes: [30, 45],
    whyItFits: [
      'Walking on sand all day asks more of your legs than walking anywhere else.',
      'Short enough to fit between the beach and dinner.',
      'You keep your clothes on — it is only feet and lower legs.',
    ],
    whatToExpect: [
      'Foot reflexology: firm, worked pressure through the soles, arches and heels.',
      'Calves and lower legs included, which is what makes it feel like a whole reset.',
      'Cool towels afterwards if the day has been hot.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 4,
  },
  {
    id: 'jrn-neck-shoulders',
    slug: 'neck-and-shoulder-rescue',
    name: 'Neck & Shoulder Rescue',
    tagline: 'You already know exactly where it is.',
    description:
      'For the knot you have been carrying since the airport — or since the office you are supposed to be forgetting. Nothing else, just the one place, properly.',
    recommendedServiceIds: ['svc-back'],
    alternativeServiceIds: ['svc-deep'],
    guestTags: ['targeted'],
    occasionTags: ['solo', 'first-massage'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['back-neck-shoulders'],
    intensity: 'firm',
    durationMinutes: [30, 45],
    whyItFits: [
      'You can point at the spot, which means we can go straight to it.',
      'Short, focused and surprisingly effective.',
      'Easy to add to a day that is already full.',
    ],
    whatToExpect: [
      'Concentrated work across the back, neck and shoulders.',
      'Firm pressure into the tight bands, eased off the moment you say so.',
      'A little stretching through the neck at the end if it helps.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 5,
  },
  {
    id: 'jrn-exhale',
    slug: 'island-exhale',
    name: 'Island Exhale',
    tagline: 'No agenda. Nowhere to be.',
    description:
      'The one to book when the answer to "what do you need" is simply "less". Warm coconut and aromatic oils, slow hands, and an hour where nothing is asked of you.',
    recommendedServiceIds: ['svc-aroma'],
    alternativeServiceIds: ['svc-relax', 'svc-stone'],
    guestTags: ['switch-off', 'unsure'],
    occasionTags: ['solo', 'couple', 'celebration'],
    timingTags: ['afternoon', 'golden-hour', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'You are not sore, you are just done — and that deserves its own massage.',
      'Scented, warm and slow from beginning to end.',
      'One of those hours you remember for the rest of the trip.',
    ],
    whatToExpect: [
      'An aromatherapy massage with warm coconut oil and an aroma you choose.',
      'Flowing full-body strokes with no deep work at all.',
      'Time built in at the end so you are not rushed off the table.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 6,
  },
  {
    id: 'jrn-sleep',
    slug: 'sleep-and-unwind',
    name: 'Sleep & Unwind',
    tagline: 'For the last hour of the day.',
    description:
      'A quiet evening session designed to end with you sleeping properly. Warm, slow and deliberately unexciting, in the best possible way.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-stone', 'svc-aroma'],
    guestTags: ['switch-off', 'gentle'],
    occasionTags: ['solo', 'couple'],
    timingTags: ['evening', 'before-sleep'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'head-scalp'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Holidays are strangely tiring, and hotel beds are strangely unfamiliar.',
      'Timed for the end of the evening so you can go straight to bed.',
      'In your room, if you would rather not go out again afterwards.',
    ],
    whatToExpect: [
      'Slow full-body work with warm oil and very little talking.',
      'A long finish on the scalp, temples and neck.',
      'Lights low, and we leave quietly.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 7,
  },
  {
    id: 'jrn-golden-hour',
    slug: 'golden-hour-reset',
    name: 'Golden Hour Reset',
    tagline: 'On your terrace, while the light goes gold.',
    description:
      'A massage timed to the best hour of the Caribbean day. Our table on your balcony, terrace or garden, and the late sun doing the rest.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-aroma'],
    guestTags: ['switch-off', 'celebrating', 'unsure'],
    occasionTags: ['couple', 'solo', 'date-night', 'celebration'],
    timingTags: ['golden-hour', 'afternoon'],
    venueTags: ['terrace', 'villa'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60],
    whyItFits: [
      'The light here between five and seven is the reason people come back.',
      'Outside in your own space, with the sky doing half the work.',
      'Relaxing rather than deep, so you can go straight to dinner afterwards.',
    ],
    whatToExpect: [
      'A full-body relaxing massage on our table, set up in the shade you have.',
      'Draped with towels throughout, so it stays comfortable and private.',
      'We work around the weather — if the wind turns, we move you indoors.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Golden hour',
    image: '',
    featured: false,
    order: 8,
  },
  {
    id: 'jrn-honeymoon',
    slug: 'couples-honeymoon-ritual',
    name: 'Couples Honeymoon Ritual',
    tagline: 'Side by side, and nothing to organise.',
    description:
      'Two therapists, two tables, one quiet room. The version to book when the evening is supposed to be memorable rather than merely pleasant.',
    recommendedServiceIds: ['svc-couples'],
    alternativeServiceIds: ['svc-aroma', 'svc-stone'],
    guestTags: ['celebrating', 'with-someone'],
    occasionTags: ['honeymoon', 'anniversary', 'date-night', 'couple', 'celebration'],
    timingTags: ['golden-hour', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'You are celebrating something, and this is an hour you spend together.',
      'Two therapists, so you both start and finish at the same moment.',
      'Set up in your room or out on your terrace — whichever suits the evening.',
    ],
    whatToExpect: [
      'Two full-body relaxing massages, side by side, at the same pace.',
      'Warm coconut oil and an aroma you both pick.',
      'Everything set up and cleared away by us.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'For two',
    image: '',
    featured: true,
    order: 9,
  },
  {
    id: 'jrn-together',
    slug: 'together-in-paradise',
    name: 'Together in Paradise',
    tagline: 'For whoever you are travelling with.',
    description:
      'Not every pair on holiday is a couple. Two tables side by side for friends, sisters, a parent and a grown-up child — same hour, same room, no assumptions.',
    recommendedServiceIds: ['svc-couples'],
    alternativeServiceIds: ['svc-relax', 'svc-back'],
    guestTags: ['with-someone', 'switch-off'],
    occasionTags: ['friends', 'family', 'couple', 'birthday', 'celebration'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'You are travelling together, so you may as well relax together.',
      'Two therapists working at the same time, in the same room.',
      'You can each choose your own pressure — nobody has to compromise.',
    ],
    whatToExpect: [
      'Two massages side by side, tailored separately.',
      'One of you can have it firm while the other has it gentle.',
      'Booked as one appointment, so there is nothing to coordinate.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 10,
  },
  {
    id: 'jrn-four-hands',
    slug: 'four-hands-indulgence',
    name: 'Four Hands Indulgence',
    tagline: 'Two therapists. One hour. Complete overkill, deliberately.',
    description:
      'Two pairs of hands working in time with each other. It is the most indulgent hour we offer, and the one guests describe afterwards as the strangest and best massage of their lives.',
    recommendedServiceIds: ['svc-fourhands'],
    alternativeServiceIds: ['svc-stone', 'svc-aroma'],
    guestTags: ['celebrating', 'switch-off'],
    occasionTags: ['birthday', 'anniversary', 'celebration', 'solo'],
    timingTags: ['afternoon', 'evening', 'golden-hour'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'You are marking something, and this is the treat version.',
      'Two therapists means twice as much happens in the same hour.',
      'Impossible to think about anything else while it is going on.',
    ],
    whatToExpect: [
      'Two therapists working in mirrored, synchronised strokes.',
      'Full body, warm oil, and a pace that never lets your mind wander back.',
      'Best booked for 90 minutes if the day allows.',
    ],
    safetyFlags: [],
    avoidTags: ['pregnant'],
    badge: 'Indulgent',
    image: '',
    featured: false,
    order: 11,
  },
  {
    id: 'jrn-gentle',
    slug: 'gentle-comfort',
    name: 'Gentle Comfort',
    tagline: 'Comfort over intensity, always.',
    description:
      'For a first massage, for a body that prefers to be treated kindly, and for anyone who has ever left a massage sore. Light pressure, careful positioning, and every part of it adjustable.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-reflex', 'svc-aroma'],
    guestTags: ['gentle', 'unsure', 'switch-off'],
    occasionTags: ['first-massage', 'solo', 'family'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body'],
    intensity: 'gentle',
    durationMinutes: [60],
    whyItFits: [
      'Massage should never be something you endure.',
      'Light, slow pressure the whole way through.',
      'Every body is different — we adjust pressure, positioning and support so the hour is comfortable for yours.',
    ],
    whatToExpect: [
      'A relaxing massage kept deliberately light throughout.',
      'Extra cushions and bolsters wherever they help you settle.',
      'You can change your mind about pressure, position or music at any point.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Welcoming',
    image: '',
    featured: true,
    order: 12,
  },
  {
    id: 'jrn-prenatal',
    slug: 'prenatal-comfort',
    name: 'Prenatal Comfort',
    tagline: 'Supported, side-lying, and entirely unhurried.',
    description:
      'A massage for pregnancy, given by a therapist trained for it. Side-lying with proper support, gentle throughout, and focused on the lower back, hips and legs that carry the most.',
    recommendedServiceIds: ['svc-prenatal'],
    alternativeServiceIds: [],
    guestTags: ['expecting', 'gentle'],
    occasionTags: ['solo', 'first-massage'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['back-neck-shoulders', 'legs-feet'],
    intensity: 'gentle',
    durationMinutes: [60],
    whyItFits: [
      'Carrying a pregnancy through a hot climate is its own kind of tiring.',
      'Side-lying with cushions, so there is no lying face down.',
      'Gentle from start to finish, with the lower back and legs getting most of the time.',
    ],
    whatToExpect: [
      'A prenatal massage from a therapist trained in it.',
      'Supported side-lying position with bolsters and pillows.',
      'Tell us anything your doctor or midwife has advised, and we will work around it — and if you would rather speak to us first, message us and we will talk it through.',
    ],
    safetyFlags: ['prenatal-safe'],
    avoidTags: [],
    badge: 'Prenatal',
    image: '',
    featured: false,
    order: 13,
  },
  {
    id: 'jrn-coconut',
    slug: 'coconut-island-ritual',
    name: 'Coconut Island Ritual',
    tagline: 'Salt, sand and sunscreen, undone.',
    description:
      'The longer, slower one. A coconut and coffee scrub first, then a warm aromatic massage — for skin that has spent a week in salt water and factor fifty.',
    recommendedServiceIds: ['svc-scrub'],
    alternativeServiceIds: ['svc-aroma', 'svc-aftersun'],
    guestTags: ['switch-off', 'celebrating'],
    occasionTags: ['celebration', 'birthday', 'anniversary', 'solo', 'couple'],
    timingTags: ['morning', 'afternoon'],
    venueTags: ['room', 'villa'],
    focusTags: ['skin', 'full-body'],
    intensity: 'relaxing',
    durationMinutes: [90],
    whyItFits: [
      'A week of sea and sunscreen leaves skin wanting something.',
      'Ninety minutes, so it is an event rather than an errand.',
      'You leave smelling of coconut, which is the correct way to leave the Caribbean.',
    ],
    whatToExpect: [
      'A coconut and coffee scrub, rinsed off, then a warm aromatherapy massage.',
      'Done where you are staying, so the shower is a few steps away.',
      'Not one for freshly sunburned skin — if you have caught the sun, tell us and we will suggest something kinder.',
    ],
    safetyFlags: [],
    avoidTags: ['sunburn'],
    badge: '',
    image: '',
    featured: false,
    order: 14,
  },
  {
    id: 'jrn-island-week',
    slug: 'your-island-week',
    name: 'Your Island Week',
    tagline: 'Three massages, spread across the whole trip.',
    description:
      'Not one massage but a shape for the week: something on arrival, something after the big excursion, and something on the last evening. Booked together, planned once, and rearranged whenever your plans change.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-deep', 'svc-aroma'],
    guestTags: ['just-arrived', 'unsure', 'switch-off'],
    occasionTags: ['couple', 'honeymoon', 'friends', 'solo', 'celebration'],
    timingTags: ['multi-day', 'arrival-day', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'balanced',
    durationMinutes: [60, 90],
    whyItFits: [
      'You are here for several days, and one massage on the last afternoon is a missed opportunity.',
      'Each session does a different job, so they do not blur into one another.',
      'Arranged in one conversation instead of three.',
    ],
    whatToExpect: [
      'On arrival: a relaxing full-body massage to put the travelling behind you.',
      'Mid-trip: firmer, focused work on whatever the excursions did to you.',
      'Last evening: something slow and aromatic, so you fly home already rested.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'All week',
    image: '',
    featured: false,
    order: 15,
  },
]
