import type { MassageJourney } from './types'

/**
 * The Spanish journey seed.
 *
 * Written, not translated. The English copy has an English rhythm — the dry
 * asides, the understatement — and rendering that word for word produces the
 * flat Spanish every hotel website in Punta Cana already has. These say the
 * same thing the way it would actually be said here: warm, direct, usted.
 *
 * Vocabulary choices are deliberately neutral-Caribbean rather than peninsular:
 * "masaje relajante", not "masaje de relajación"; "la playa" and "su
 * habitación"; no vosotros anywhere.
 *
 * Every tag, id and slug is identical to `journeys.ts` — those are canonical
 * keys, and the matcher has to score both documents the same way.
 */
export const journeysEs: MassageJourney[] = [
  {
    id: 'jrn-arrival',
    slug: 'just-arrived-reset',
    name: 'Recién llegada',
    tagline: 'Su cuerpo sigue en el avión. Nosotras lo traemos aquí.',
    description:
      'El primer masaje del viaje, el que marca el final del traslado. Trabajo de cuerpo completo, sin prisa, para que los hombros bajen y las vacaciones empiecen de verdad.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-aroma', 'svc-reflex'],
    guestTags: ['just-arrived', 'unsure'],
    occasionTags: ['solo', 'couple', 'first-massage'],
    timingTags: ['arrival-day', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Acaba de viajar, y viajar deja el cuerpo duro en los lugares más raros.',
      'Lento y tibio, para que la acomode en vez de despertarla.',
      'Vamos a su habitación, así no tiene que salir a ningún lado.',
    ],
    whatToExpect: [
      'Masaje relajante de cuerpo completo, sin apuro.',
      'Más tiempo en hombros, espalda baja y pies: lo que más castiga un vuelo largo.',
      'Aceite de coco tibio, música suave y nada de conversación si no la quiere.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Empiece aquí',
    image: '',
    featured: true,
    order: 1,
  },
  {
    id: 'jrn-jetlag',
    slug: 'jet-lag-reset',
    name: 'Adiós al jet lag',
    tagline: 'Para la noche en que su cuerpo jura que son las 4 de la mañana.',
    description:
      'Una sesión de noche pensada para que duerma en hora local. Trabajo largo y rítmico con buen tiempo en los pies, que es donde se queda trancado un cuerpo que cambió de huso horario.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-reflex', 'svc-stone'],
    guestTags: ['just-arrived', 'switch-off'],
    occasionTags: ['solo', 'couple'],
    timingTags: ['arrival-day', 'evening', 'before-sleep'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'legs-feet'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Su reloj interno todavía anda por el Atlántico.',
      'Se reserva para la noche, así termina lista para la cama.',
      'Suave, para que nada la vuelva a despertar.',
    ],
    whatToExpect: [
      'Cuerpo completo, lento, con movimientos largos y repetidos.',
      'Un buen rato dedicado a pies y pantorrillas.',
      'Termina en cuero cabelludo y cuello, que es lo que normalmente termina de dormir a la gente.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 2,
  },
  {
    id: 'jrn-adventure',
    slug: 'after-adventure-recovery',
    name: 'Después de la aventura',
    tagline: 'El buggy valió la pena. Su espalda opina distinto.',
    description:
      'Para el día después del tour en cuatrimoto, el catamarán, la tirolesa o dieciocho hoyos. Trabajo firme y dirigido a todo lo que se sacudió, remó o caminó más de la cuenta.',
    recommendedServiceIds: ['svc-deep'],
    alternativeServiceIds: ['svc-back', 'svc-relax'],
    guestTags: ['after-adventure', 'targeted'],
    occasionTags: ['friends', 'couple', 'solo'],
    timingTags: ['after-excursion', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'back-neck-shoulders', 'legs-feet'],
    intensity: 'firm',
    durationMinutes: [60, 90],
    whyItFits: [
      'Ayer hizo algo buenísimo y hoy lo siente completo.',
      'Presión firme y precisa donde de verdad molesta.',
      'Usted nos dice dónde duele; ahí ponemos el tiempo.',
    ],
    whatToExpect: [
      'Masaje descontracturante y deportivo, más lento y más firme que uno relajante.',
      'Atención concentrada en espalda, hombros, piernas y donde usted señale.',
      'Vamos midiendo la presión con usted: firme tiene que sentirse rico, nunca algo que hay que aguantar.',
    ],
    safetyFlags: [],
    avoidTags: ['pregnant'],
    badge: 'El más pedido',
    image: '',
    featured: true,
    order: 3,
  },
  {
    id: 'jrn-feet-legs',
    slug: 'feet-and-legs-reset',
    name: 'Pies y piernas',
    tagline: 'Sus piernas tuvieron un día largo.',
    description:
      'Para quien caminó la playa entera, recorrió el mercado o lleva de pie desde el desayuno. Todo el tiempo va de la cintura para abajo, que es donde cayó el día.',
    recommendedServiceIds: ['svc-reflex'],
    alternativeServiceIds: ['svc-relax', 'svc-lymph'],
    guestTags: ['after-adventure', 'targeted', 'switch-off'],
    occasionTags: ['solo', 'friends', 'family'],
    timingTags: ['afternoon', 'evening', 'after-excursion'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['legs-feet'],
    intensity: 'balanced',
    durationMinutes: [30, 45],
    whyItFits: [
      'Caminar en arena todo el día le pide más a las piernas que caminar en cualquier otro lado.',
      'Corto, cabe entre la playa y la cena.',
      'Se queda con su ropa puesta: son pies y piernas nada más.',
    ],
    whatToExpect: [
      'Reflexología podal: presión firme y trabajada en planta, arco y talón.',
      'Incluye pantorrillas, que es lo que lo convierte en un descanso completo.',
      'Toallas frías al final si el día estuvo caliente.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 4,
  },
  {
    id: 'jrn-neck-shoulders',
    slug: 'neck-and-shoulder-rescue',
    name: 'Rescate de cuello y hombros',
    tagline: 'Usted ya sabe exactamente dónde es.',
    description:
      'Para ese nudo que carga desde el aeropuerto, o desde la oficina que se supone que está olvidando. Nada más: ese punto, bien hecho.',
    recommendedServiceIds: ['svc-back'],
    alternativeServiceIds: ['svc-deep'],
    guestTags: ['targeted'],
    occasionTags: ['solo', 'first-massage'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['back-neck-shoulders'],
    intensity: 'firm',
    durationMinutes: [30, 45],
    whyItFits: [
      'Usted puede señalar el punto, así que vamos directo ahí.',
      'Corto, concentrado y sorprendentemente efectivo.',
      'Fácil de meter en un día que ya está lleno.',
    ],
    whatToExpect: [
      'Trabajo concentrado en espalda alta, cuello y hombros.',
      'Presión firme sobre las bandas tensas, que aflojamos apenas usted lo diga.',
      'Un poco de estiramiento de cuello al final si ayuda.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 5,
  },
  {
    id: 'jrn-exhale',
    slug: 'island-exhale',
    name: 'Respiro isleño',
    tagline: 'Sin agenda. Sin tener que estar en ningún lado.',
    description:
      'El que se reserva cuando la respuesta a "¿qué necesita?" es sencillamente "menos". Aceites tibios de coco y aroma, manos lentas, y una hora en la que nadie le pide nada.',
    recommendedServiceIds: ['svc-aroma'],
    alternativeServiceIds: ['svc-relax', 'svc-stone'],
    guestTags: ['switch-off', 'unsure'],
    occasionTags: ['solo', 'couple', 'celebration'],
    timingTags: ['afternoon', 'golden-hour', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'No está adolorida, está agotada, y eso merece su propio masaje.',
      'Con aroma, tibio y lento de principio a fin.',
      'De esas horas que uno recuerda el resto del viaje.',
    ],
    whatToExpect: [
      'Masaje de aromaterapia con aceite de coco tibio y el aroma que usted elija.',
      'Movimientos envolventes de cuerpo completo, sin nada profundo.',
      'Dejamos tiempo al final para que no salga corriendo de la camilla.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: true,
    order: 6,
  },
  {
    id: 'jrn-sleep',
    slug: 'sleep-and-unwind',
    name: 'Dormir tranquila',
    tagline: 'Para la última hora del día.',
    description:
      'Una sesión de noche pensada para terminar durmiendo bien. Tibia, lenta y deliberadamente poco emocionante, en el mejor sentido.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-stone', 'svc-aroma'],
    guestTags: ['switch-off', 'gentle'],
    occasionTags: ['solo', 'couple'],
    timingTags: ['evening', 'before-sleep'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body', 'head-scalp'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Las vacaciones cansan de una forma rara, y las camas de hotel nunca son las de uno.',
      'A la hora de acostarse, para que pase directo a la cama.',
      'En su habitación, si prefiere no volver a salir.',
    ],
    whatToExpect: [
      'Cuerpo completo lento, con aceite tibio y muy poca conversación.',
      'Un final largo en cuero cabelludo, sienes y cuello.',
      'Luz baja, y nos vamos en silencio.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 7,
  },
  {
    id: 'jrn-golden-hour',
    slug: 'golden-hour-reset',
    name: 'Hora dorada',
    tagline: 'En su terraza, mientras la luz se pone dorada.',
    description:
      'Un masaje a la mejor hora del día caribeño. Nuestra camilla en su balcón, su terraza o su jardín, y el sol de la tarde haciendo el resto.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-aroma'],
    guestTags: ['switch-off', 'celebrating', 'unsure'],
    occasionTags: ['couple', 'solo', 'date-night', 'celebration'],
    timingTags: ['golden-hour', 'afternoon'],
    venueTags: ['terrace', 'villa'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60],
    whyItFits: [
      'La luz de aquí entre las cinco y las siete es la razón por la que la gente vuelve.',
      'Al aire libre, en su propio espacio, con el cielo haciendo la mitad del trabajo.',
      'Relajante y no profundo, así puede irse directo a cenar.',
    ],
    whatToExpect: [
      'Masaje relajante de cuerpo completo en nuestra camilla, montada en la sombra que tenga.',
      'Cubierta con toallas todo el tiempo, para que sea cómodo y privado.',
      'Nos adaptamos al clima: si cambia el viento, la pasamos bajo techo.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Hora dorada',
    image: '',
    featured: false,
    order: 8,
  },
  {
    id: 'jrn-honeymoon',
    slug: 'couples-honeymoon-ritual',
    name: 'Ritual de luna de miel',
    tagline: 'Uno al lado del otro, y nada que organizar.',
    description:
      'Dos terapeutas, dos camillas, una sala tranquila. La versión para cuando la noche tiene que ser memorable y no solamente agradable.',
    recommendedServiceIds: ['svc-couples'],
    alternativeServiceIds: ['svc-aroma', 'svc-stone'],
    guestTags: ['celebrating', 'with-someone'],
    occasionTags: ['honeymoon', 'anniversary', 'date-night', 'couple', 'celebration'],
    timingTags: ['golden-hour', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Están celebrando algo, y esta es una hora que pasan juntos.',
      'Dos terapeutas, así empiezan y terminan al mismo tiempo.',
      'Montado en su habitación o en su terraza, como prefieran esa noche.',
    ],
    whatToExpect: [
      'Dos masajes relajantes de cuerpo completo, lado a lado y al mismo ritmo.',
      'Aceite de coco tibio y un aroma que eligen los dos.',
      'Nosotras montamos todo y lo recogemos.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Para dos',
    image: '',
    featured: true,
    order: 9,
  },
  {
    id: 'jrn-together',
    slug: 'together-in-paradise',
    name: 'Juntos en el paraíso',
    tagline: 'Para quien sea que viene con usted.',
    description:
      'No toda pareja de viaje es una pareja. Dos camillas lado a lado para amigas, hermanos, una madre y su hijo ya grande: misma hora, misma sala, sin suposiciones.',
    recommendedServiceIds: ['svc-couples'],
    alternativeServiceIds: ['svc-relax', 'svc-back'],
    guestTags: ['with-someone', 'switch-off'],
    occasionTags: ['friends', 'family', 'couple', 'birthday', 'celebration'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Viajan juntos, así que también pueden relajarse juntos.',
      'Dos terapeutas trabajando a la vez, en la misma sala.',
      'Cada quien elige su propia presión: nadie tiene que ceder.',
    ],
    whatToExpect: [
      'Dos masajes lado a lado, adaptados por separado.',
      'Uno puede llevarlo firme mientras el otro lo lleva suave.',
      'Se reserva como una sola cita, así no hay nada que coordinar.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: '',
    image: '',
    featured: false,
    order: 10,
  },
  {
    id: 'jrn-four-hands',
    slug: 'four-hands-indulgence',
    name: 'Cuatro manos',
    tagline: 'Dos terapeutas. Una hora. Un exceso, a propósito.',
    description:
      'Dos pares de manos trabajando sincronizadas. Es la hora más indulgente que ofrecemos, y la que los huéspedes describen después como el masaje más raro y más rico de su vida.',
    recommendedServiceIds: ['svc-fourhands'],
    alternativeServiceIds: ['svc-stone', 'svc-aroma'],
    guestTags: ['celebrating', 'switch-off'],
    occasionTags: ['birthday', 'anniversary', 'celebration', 'solo'],
    timingTags: ['afternoon', 'evening', 'golden-hour'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body'],
    intensity: 'relaxing',
    durationMinutes: [60, 90],
    whyItFits: [
      'Está marcando una ocasión, y esta es la versión regalo.',
      'Dos terapeutas quiere decir que en la misma hora pasa el doble.',
      'Imposible pensar en otra cosa mientras está ocurriendo.',
    ],
    whatToExpect: [
      'Dos terapeutas trabajando en movimientos espejados y sincronizados.',
      'Cuerpo completo, aceite tibio, y un ritmo que no deja divagar.',
      'Mejor de 90 minutos si el día lo permite.',
    ],
    safetyFlags: [],
    avoidTags: ['pregnant'],
    badge: 'Un lujo',
    image: '',
    featured: false,
    order: 11,
  },
  {
    id: 'jrn-gentle',
    slug: 'gentle-comfort',
    name: 'Suave y cómodo',
    tagline: 'Comodidad antes que intensidad, siempre.',
    description:
      'Para un primer masaje, para un cuerpo que prefiere que lo traten con cariño, y para quien alguna vez salió adolorido de un masaje. Presión ligera, buena postura y todo ajustable.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-reflex', 'svc-aroma'],
    guestTags: ['gentle', 'unsure', 'switch-off'],
    occasionTags: ['first-massage', 'solo', 'family'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['full-body'],
    intensity: 'gentle',
    durationMinutes: [60],
    whyItFits: [
      'Un masaje nunca debería ser algo que hay que aguantar.',
      'Presión ligera y lenta de principio a fin.',
      'Cada cuerpo es distinto: ajustamos presión, postura y apoyos para que la hora sea cómoda para el suyo.',
    ],
    whatToExpect: [
      'Un masaje relajante mantenido a propósito en presión ligera.',
      'Cojines y apoyos donde le ayuden a acomodarse.',
      'Puede cambiar de opinión sobre presión, postura o música en cualquier momento.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Para todos',
    image: '',
    featured: true,
    order: 12,
  },
  {
    id: 'jrn-prenatal',
    slug: 'prenatal-comfort',
    name: 'Comodidad prenatal',
    tagline: 'De lado, bien apoyada y sin ninguna prisa.',
    description:
      'Un masaje para el embarazo, con una terapeuta formada para darlo. De lado y con buen apoyo, suave todo el tiempo, y enfocado en la espalda baja, las caderas y las piernas, que son las que más cargan.',
    recommendedServiceIds: ['svc-prenatal'],
    alternativeServiceIds: [],
    guestTags: ['expecting', 'gentle'],
    occasionTags: ['solo', 'first-massage'],
    timingTags: ['morning', 'afternoon', 'evening'],
    venueTags: ['room', 'villa'],
    focusTags: ['back-neck-shoulders', 'legs-feet'],
    intensity: 'gentle',
    durationMinutes: [60],
    whyItFits: [
      'Llevar un embarazo en este calor cansa de su propia manera.',
      'De lado y con cojines, así no hay que acostarse boca abajo.',
      'Suave de principio a fin, con la mayor parte del tiempo en espalda baja y piernas.',
    ],
    whatToExpect: [
      'Masaje prenatal con una terapeuta formada en él.',
      'Postura de lado con cojines y almohadas de apoyo.',
      'Cuéntenos lo que le haya indicado su médico o partera y trabajamos alrededor de eso; y si prefiere hablar con nosotras antes, escríbanos y lo conversamos.',
    ],
    safetyFlags: ['prenatal-safe'],
    avoidTags: [],
    badge: 'Prenatal',
    image: '',
    featured: false,
    order: 13,
  },
  {
    id: 'jrn-coconut',
    slug: 'coconut-island-ritual',
    name: 'Ritual de coco',
    tagline: 'Sal, arena y protector solar, deshechos.',
    description:
      'El más largo y más lento. Primero un exfoliante de coco y café, después un masaje tibio con aroma: para una piel que pasó una semana entre agua salada y factor cincuenta.',
    recommendedServiceIds: ['svc-scrub'],
    alternativeServiceIds: ['svc-aroma', 'svc-aftersun'],
    guestTags: ['switch-off', 'celebrating'],
    occasionTags: ['celebration', 'birthday', 'anniversary', 'solo', 'couple'],
    timingTags: ['morning', 'afternoon'],
    venueTags: ['room', 'villa'],
    focusTags: ['skin', 'full-body'],
    intensity: 'relaxing',
    durationMinutes: [90],
    whyItFits: [
      'Una semana de mar y protector solar deja la piel pidiendo algo.',
      'Noventa minutos: es un plan, no un trámite.',
      'Sale oliendo a coco, que es la forma correcta de salir del Caribe.',
    ],
    whatToExpect: [
      'Exfoliante de coco y café, se enjuaga, y después masaje tibio de aromaterapia.',
      'Donde se está quedando, así la ducha queda a unos pasos.',
      'No es para piel recién quemada por el sol: si cogió sol, díganos y le sugerimos algo más amable.',
    ],
    safetyFlags: [],
    avoidTags: ['sunburn'],
    badge: '',
    image: '',
    featured: false,
    order: 14,
  },
  {
    id: 'jrn-island-week',
    slug: 'your-island-week',
    name: 'Su semana en la isla',
    tagline: 'Tres masajes, repartidos en todo el viaje.',
    description:
      'No un masaje sino una forma para la semana: algo al llegar, algo después de la excursión grande, y algo la última noche. Se reserva junto, se planifica una vez, y se reacomoda cuando cambien sus planes.',
    recommendedServiceIds: ['svc-relax'],
    alternativeServiceIds: ['svc-deep', 'svc-aroma'],
    guestTags: ['just-arrived', 'unsure', 'switch-off'],
    occasionTags: ['couple', 'honeymoon', 'friends', 'solo', 'celebration'],
    timingTags: ['multi-day', 'arrival-day', 'evening'],
    venueTags: ['room', 'villa', 'terrace'],
    focusTags: ['full-body'],
    intensity: 'balanced',
    durationMinutes: [60, 90],
    whyItFits: [
      'Se queda varios días, y un solo masaje la última tarde es una oportunidad perdida.',
      'Cada sesión hace un trabajo distinto, así no se confunden entre ellas.',
      'Se organiza en una conversación en vez de tres.',
    ],
    whatToExpect: [
      'Al llegar: masaje relajante de cuerpo completo para dejar atrás el viaje.',
      'A mitad del viaje: trabajo más firme y dirigido a lo que le hicieron las excursiones.',
      'La última noche: algo lento y con aroma, para volar de vuelta ya descansada.',
    ],
    safetyFlags: [],
    avoidTags: [],
    badge: 'Toda la semana',
    image: '',
    featured: false,
    order: 15,
  },
]
